name: test

on: pull_request

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Test
      run: |
        npm ci
        npm run test

  e2e:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      uses: cypress-io/github-action@v5
      with:
        browser: chrome
